### PR TITLE
Pushhandler

### PR DESCRIPTION
**Pull request by DanielMorsing**
This is the initial implementation of server push. There's still a lot to do. Consider this pull request more of a request for comments on the design rather than final code push.

### CODE REVIEW

**Comment by brk0v** [comment]
You've forgotten to increment `sc.curOpenStreams` in `startPushPromise` function. Because of this we can get `RST_STREAM` from server with `PROTOCOL_ERROR`.

Sends from here:

```go
func (sc *serverConn) processHeaderBlockFragment(st *stream, frag []byte, end bool) error {   

        ...

	if sc.curOpenStreams > sc.advMaxStreams {
		// "Endpoints MUST NOT exceed the limit set by their
		// peer. An endpoint that receives a HEADERS frame
		// that causes their advertised concurrent stream
		// limit to be exceeded MUST treat this as a stream
		// error (Section 5.4.2) of type PROTOCOL_ERROR or
		// REFUSED_STREAM."
		if sc.unackedSettings == 0 {
			// They should know better.
			return StreamError{st.id, ErrCodeProtocol}
		}
```

Cause it decrements here. And in case of 0 we get: 4294967295.

```go
func (sc *serverConn) closeStream(st *stream, err error) {
	sc.serveG.check()
	if st.state == stateIdle || st.state == stateClosed {
		panic(fmt.Sprintf("invariant; can't close stream in state %v", st.state))
	}
	st.state = stateClosed
	sc.curOpenStreams--
```

**Comment by brk0v** [comment]
You've missed to implement push counter for streams in the ```startPushPromise``` function. Because of this we can get ```RST_STREAM``` from server with ```PROTOCOL_ERROR```. It tries to decrement counter curOpenStreams:

```go
func (sc *serverConn) closeStream(st *stream, err error) {
    sc.serveG.check()
    if st.state == stateIdle || st.state == stateClosed {
        panic(fmt.Sprintf("invariant; can't close stream in state %v", st.state))
    }
    st.state = stateClosed
    sc.curOpenStreams--
```

 And in case of 0 we get: 4294967295. And then we try to check it here:

```go
func (sc *serverConn) processHeaderBlockFragment(st *stream, frag []byte, end bool) error {   

        ...

    if sc.curOpenStreams > sc.advMaxStreams {
        // "Endpoints MUST NOT exceed the limit set by their
        // peer. An endpoint that receives a HEADERS frame
        // that causes their advertised concurrent stream
        // limit to be exceeded MUST treat this as a stream
        // error (Section 5.4.2) of type PROTOCOL_ERROR or
        // REFUSED_STREAM."
        if sc.unackedSettings == 0 {
            // They should know better.
            return StreamError{st.id, ErrCodeProtocol}
        }
```

I could not find how to add patch here so I send new pull request: https://github.com/bradfitz/http2/pull/34

**Comment by DanielMorsing** [comment]
Sorry about leaving this for so long.

Right now there are multiple issues with the code. Along with the curopenstreams issue that you discovered, we also need to take into account the clientMaxStreams variable that limits the amount of push promises that a server can initiate with a client concurrently.

I have some free time today, so I'll probably push some new code soon.

**Comment by DanielMorsing** [comment]
Nevermind, I looks like you fixed this independently. I'll wait for Brad to have a look. He's on vacation though, so it might be a while.

**Comment by bradfitz** [comment]
This repo just moved into the official Go repo.

See https://github.com/bradfitz/http2/blob/master/README for the move details.

File new bugs at: https://github.com/golang/go/issues/new?title=x/net/http2:+

Closing this PR as we're now using Gerrit for code review. Please file a bug or send the review to Gerrit if this is still relevant. Sorry for how long this languished here.

**Pull request closed without merging**
