### PR TITLE
server: fix leak on writeHeaders during RST_STREAM from client

### LINKED ISSUE #45: writeHeaders leaks goroutines on RST_STREAM until end of connection
This was originally mentioned in #33. I've got a fix, just need to write a test.

@bradfitz I've got another fix for another goroutine leak in readFrames (didn't handle doneServing and blocks forever). Want another issue/checkin for that?

### PR DESCRIPTION
**Pull request by pabbott0**
Fixes #45 

Hoping I didn't muck about with too many internals in the test. That was a pain to write.

### CODE REVIEW

**Comment by pabbott0** [comment]
Upon further consideration, this might have introduced a race between the writeFrameFromHandler reply channel and the stream close detection. The reply channel ends up getting written to but stream.cw getting closed may be detected before consuming the error, which is very bad considering the channel gets reused. I have my instance  running with new reply channel per write at the moment to get around this, but there are still more issues.

When I have stream.cw breaking the blocked selects for #45 and #46, there are a couple more selects showing up that can get blocked forever: writeDataFromHandler and writeFrameFromHandler. After adding stream.cw checks to both of those as well, there's STILL another leak in writeDataFromHandler where stream.cw never gets closed but the connection hangs in select with a stream.state of HalfClosedRemote.

At this point, I don't know if I'm making actual progress or just trading one set of races for another.

**Comment by pabbott0** [comment]
I've changed my approach. Instead of catching stream resets all over the place I have made sure that a frame write message always gets a reply (or channel close) on its done chan in all instances. This has removed all writer leaks that showed up with @jaredfolkins "mash refresh" reproduction method, and doesn't introduce any racy behavior that I can see.

It still needs a bit of cleanup, but I'd like to know if my approach is acceptable (or if you have any other comments).

**Comment by bradfitz** [comment]
General approach seems fine.

**Comment by pabbott0** [comment]
Yes, the writesched part is necessary since the case still triggers in my testing. That's why I'm allocating the new done chans in writeChunk(), so I can close them when forgetStream cleans up.

It would be possible to use a single channel if I were to iterate through the queued frameWriteMsgs of writeSched in closeStream() and send errors, but that would require blocking sends since the done chan would be shared across all queued writes that have a non-nil done chan. I really did not want to do a blocking send in the serve goroutine. Actually, I don't even need to do a blocking send, but manually polling through the queued frameWriteMsgs' done chans to make sure they all get a response also sounds dodgy.

Another thing I disliked about the shared done channel is that, due to the writesched queue, you can have multiple frameWriteMsgs open at the same time listening for a reply on the same done channel. The result is that a blocked writer that receives the done chan send is not necessarily the one that was completed.

If you're dead set against allocating those channels in writeChunk(), a pre-allocated pool would probably be better so that a 1:1 correspondence between frameWriteMsgs and done chans can be maintained.

**Comment by bradfitz** [comment]
Fixed upstream in c94bffa210e2 with credit to @pabbott0, and using your tests and very similar fix. Thanks!

**Comment by pabbott0** [comment]
Ah, so you went the pooling route. I didn't know sync.Pool existed until I read the patch, and wish I had. Would have probably stopped a couple of my hacky uses of a buffered channel as an object pool in the past. Glad the test (and some of the fix) helped.

**Pull request closed without merging**
