### PR TITLE
transport: support for request bodies, flow control, trailers

### PR DESCRIPTION
**Pull request by bgentry**
This adds rudimentary support for request bodies.

Data frames are written synchronously with each call the `io.Copy()` makes to `dataFrameWriter.Write()`. After the copy has finished, an empty data frame is written with the EndStream flag.

One thing that's not supported here is Trailers. To do that, we'd have to avoid setting the EndStream flag on the last data frame if there are trailers (another header frame) and optionally, continuation frames following the end of the data frames. Is that worth adding now or should I just drop the TODO for it?

Also, padding in data frames is not yet supported (as the Framer doesn't support it yet).

### CODE REVIEW

**Comment by bradfitz** [comment]
I would expect this to involve flow control?

/cc @bmizerany 

I'm going to be Internet-less for 2 weeks starting tomorrow.

**Comment by bgentry** [comment]
@bradfitz yeah, well there is no flow control at all in the client yet afaict. I see you've got support for that in the server, though. Do you think that should be part of the same PR? Doesn't look like it would be too bad to do the same sort of thing in the client if you want me to try to add it here.

Do you have any thoughts regarding Trailer support?

**Comment by bradfitz** [comment]
We should support Trailers soon. I was going to say that the first commit should at least have a solid plan for them, but if you have a solid plan, it's not much more work to just do them. But either way: a good TODO with a full plan, or include them in the first version.

I don't want to merge any commit that sends data without flow control, though.

**Comment by bgentry** [comment]
I've added some basic flow control support (with a test) and support for trailers (without a test). Testing trailers will be easier once the server supports it. The flow control does have some remaining issues, though. There are a few places where I wasn't sure how to handle errors.

Also, the Transport currently doesn't schedule frame writes the way the Server does. Is that part of your eventual plan for this? I think the vast majority of logic could be shared between the serverConn and clientConn. Things like flow control, conn state management, frame scheduling and prioritization could all get moved into the Framer, or to something that wraps it such as a `conn` type.

**Comment by bgentry** [comment]
I've got a *really* rough version of the shared conn logic that at least passes all existing tests: https://github.com/bradfitz/http2/compare/bradfitz:master...bgentry:share-conn-logic

Planning to do some more cleanup on it and finish implementing request bodies. I think I can further condense some of the logic in `conn` that's similar between client and server conns.

**Comment by bgentry** [comment]
Closing this in favor of #36.

**Pull request closed without merging**
